spring:
  datasource:
    url: ${DATABASE_URL}  # HerokuのDATABASE_URLを使用
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true  # 開発中はtrue、本番環境ではfalseに

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # 開発中はfalse、本番環境ではtrueに

  server:
    error:
      whitelabel:
        enabled: false
    port: ${PORT:8080}
