spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    h2:
      console:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # 開発中はfalse、本番環境ではtrueに

  server:
    error:
      whitelabel:
        enabled: false
    port: ${PORT:8080}
